/*
  PORTFOLIO CONTENT — edit this file to update the whole website.
  - Add/reorder projects by moving objects in `projects`; set featured: true for Home.
  - Set visible: false to hide unfinished work. Empty links are automatically hidden.
  - Replace image paths and cvPath after adding your files in assets/.
*/
const portfolioData = {
  profile: {
    name: 'Priyabrata Das', degree: 'B.Tech in Biomedical Engineering',
    institution: 'National Institute of Technology Rourkela, India',
    email: 'daspriyabrata748@gmail.com', location: '',
    photo: 'assets/images/profile.jpg', cvPath: 'assets/documents/Priyabrata_Das_CV.pdf',
    availability: 'Seeking Fall/August 2027 Direct PhD Opportunities',
    intro: 'I am a Biomedical Engineering undergraduate at the National Institute of Technology Rourkela with research experience spanning biomaterials, hydrogel characterization, molecular dynamics simulations, biomedical image analysis, and biomedical instrumentation. My primary interests lie in tissue engineering, regenerative medicine, polymer-based biomaterials, and computational approaches for understanding biomaterial–biological interactions.',
    bio: 'My academic interests connect experimental biomaterials work with computational methods for studying how material systems interact with biological environments. I am preparing for direct PhD opportunities where I can continue developing this interdisciplinary foundation.'
  },
  education: [{ degree: 'B.Tech in Biomedical Engineering', institution: 'National Institute of Technology Rourkela, India', dates: 'Current undergraduate study', detail: 'Coursework and project work spanning biomaterials, computation, and biomedical engineering.' }],
  researchInterests: ['Biomaterials', 'Tissue Engineering', 'Regenerative Medicine', 'Hydrogels', 'Bioinks', 'Mechanical Characterization of Biomaterials', 'Polymer-Based Biomaterials', 'Mechanobiology', 'Computational Biomaterials', 'Molecular Dynamics', 'GROMACS', 'Biomedical Image Analysis'],
  projects: [
    { title: 'Mechanical Characterization of Biomaterial Systems', category: 'Biomaterials & Hydrogels', status: 'Research project', institution: 'National Institute of Technology Rourkela', supervisor: '', dates: '', overview: 'Work involving dextran methacrylate, gelatin methacrylate, and alginate methacrylate systems for hydrogel formulation and characterization.', objective: 'Explore material preparation and characterization approaches for hydrogel systems.', methods: ['Hydrogel formulation', 'Rheological characterization', 'UV-assisted crosslinking', 'Swelling and degradation studies'], tools: ['Anton Paar rheometer'], contribution: 'Experimental preparation and characterization support.', outcome: 'Ongoing academic work.', image: 'assets/images/biomaterials-project.jpg', featured: true, visible: true },
    { title: 'PLGA–Membrane Molecular Dynamics Study', category: 'Computational Biomaterials', status: 'Study', institution: '', supervisor: '', dates: '', overview: 'A coarse-grained molecular dynamics study of polymer–membrane interactions.', objective: 'Use simulation and trajectory analysis to examine PLGA–membrane interactions.', methods: ['Coarse-grained molecular dynamics', 'Trajectory analysis'], tools: ['GROMACS', 'MARTINI force field'], contribution: 'Simulation setup and analysis.', outcome: 'Project work; details to be verified before public release.', image: 'assets/images/molecular-dynamics-project.jpg', featured: true, visible: true },
    { title: 'Brain Tumor Segmentation Using Deep Learning', category: 'Biomedical Image Analysis', status: 'Project', institution: '', supervisor: '', dates: '', overview: 'MRI segmentation project using a U-Net workflow and DCGAN-based data augmentation.', objective: 'Explore deep-learning methods for biomedical image segmentation.', methods: ['MRI segmentation', 'U-Net', 'DCGAN-based data augmentation'], tools: ['Python', 'PyTorch'], contribution: 'Model development and image-analysis workflow.', outcome: 'Academic project.', image: 'assets/images/brain-tumor-project.jpg', featured: true, visible: true },
    { title: 'Muscle Fatigue Monitoring Using EMG', category: 'Biomedical Instrumentation', status: 'Prototype', institution: '', supervisor: '', dates: '', overview: 'Arduino-based EMG monitoring prototype with threshold-based fatigue indication.', objective: 'Develop a simple monitoring prototype for EMG signal use.', methods: ['EMG monitoring', 'Sensor interfacing', 'Threshold-based indication'], tools: ['Arduino'], contribution: 'Prototype development and documentation.', outcome: 'Prototype project.', image: 'assets/images/emg-project.jpg', featured: false, visible: true },
    { title: 'AGRI-FLOW Compact Vertical Dryer', category: 'Industrial Design', status: 'Prototype concept', institution: '', supervisor: '', dates: '', overview: 'Compact vertical dryer concept involving moisture monitoring and a dual-pass auger approach.', objective: 'Document a practical product-development concept.', methods: ['Prototype development', 'Industrial design', 'Product documentation'], tools: [], contribution: 'Design documentation and prototype-oriented problem solving.', outcome: 'Design project.', image: 'assets/images/agriflow-project.jpg', featured: false, visible: true },
    { title: 'Multipurpose Cleaning Tool', category: 'Industrial Design', status: 'Design project', institution: '', supervisor: '', dates: '', overview: 'Industrial design application focused on product development and design documentation.', objective: 'Develop and document a prototype-oriented product concept.', methods: ['Product development', 'Design documentation'], tools: [], contribution: 'Design and documentation.', outcome: 'Design project.', image: 'assets/images/cleaning-tool-project.jpg', featured: false, visible: true }
  ],
  experience: [
    { organization: 'Institute of Life Sciences, Bhubaneswar', position: '', supervisor: '', dates: '', project: '', responsibilities: [], methods: [], skills: [], visible: true },
    { organization: 'ICMR–Regional Medical Research Centre, Bhubaneswar', position: '', supervisor: '', dates: '', project: '', responsibilities: [], methods: [], skills: [], visible: true },
    { organization: 'Jindal Stainless Limited, Jajpur', position: 'Industrial project experience', supervisor: '', dates: '', project: 'Electric arc furnace slag and chromium-loss mechanisms', responsibilities: ['Considered chromium loss mechanisms in an electric arc furnace.', 'Reviewed slag parameters, sustainable utilization of electric-arc-furnace slag, and environmental compliance.'], methods: ['Industrial process analysis'], skills: ['Technical documentation'], visible: true }
  ],
  publications: { journalArticles: [], underReview: [], inPreparation: [], preprints: [], presentations: [{ title: 'Advancing Hepatitis-B Treatment through CLIA-Based Immune Profiling and Innovative Drug Development Strategies', venue: 'Young Scientists Conclave, India International Science Festival', doi: '10.13140/RG.2.2.20983.64167', status: 'In preparation', type: 'Conference presentation', year: '' }], posters: [] },
  skills: { Experimental: ['Biomaterial preparation', 'Hydrogel formulation', 'Rheology', 'UV-assisted crosslinking', 'Swelling and degradation studies', 'Basic cell culture', 'PCR and qPCR', 'RNA isolation', 'Laboratory documentation'], Computational: ['GROMACS', 'Molecular dynamics', 'Python', 'PyTorch', 'MATLAB', 'R', 'C++', 'Data analysis', 'Biomedical image analysis'], 'Software & tools': ['Git', 'GitHub', 'Linux', 'GraphPad Prism', 'Microsoft Word', 'Microsoft Excel', 'Microsoft PowerPoint', 'Canva', 'Arduino'] },
  achievements: ['GATE Biomedical Engineering AIR 251', 'IELTS: add verified scores here', 'Industrial design applications', 'Conference participation', 'Research internships'],
  socialLinks: { github: 'https://github.com/PriyabrataDas1', linkedin: '', scholar: '', orcid: '', researchgate: '' },
  siteSettings: { baseUrl: 'https://priyabratadas1.github.io', lastUpdated: '2026' }
};
