/*
  PORTFOLIO CONTENT — edit this file to update the whole website.
  - Add/reorder projects by moving objects in `projects`; set featured: true for Home.
  - Set visible: false to hide unfinished work. Empty links are automatically hidden.
  - Replace image paths and cvPath after adding your files in assets/.
*/
const portfolioData = {
  profile: {
    name: 'Priyabrata Das', degree: 'B.Tech in Biomedical Engineering',
    institution: 'National Institute of Technology Rourkela, India',
    email: 'daspriyabrata748@gmail.com', location: '',
    photo: 'assets/images/profile.png', cvPath: 'assets/documents/Priyabrata_Das_CV.pdf',
    availability: '',
    intro: 'I am a Biomedical Engineering undergraduate at the National Institute of Technology Rourkela with research experience in biomaterials, hydrogel characterization, molecular dynamics simulations, biomedical image analysis, molecular diagnostics, and biomedical instrumentation. My primary interests lie in tissue engineering, regenerative medicine, polymer-based biomaterials, and computational approaches for understanding biomaterial–biological interactions.',
    bio: 'My academic work connects experimental biomaterials research with computational methods for studying material systems and biomedical data. I am preparing for direct PhD opportunities where I can continue developing this interdisciplinary foundation.'
  },
  education: [{ degree: 'B.Tech in Biomedical Engineering', institution: 'National Institute of Technology Rourkela, India', dates: 'Aug 2023 – Present', detail: 'CGPA: 7.33/10.' }, { degree: 'CBSE Class XII (Science – PCM)', institution: 'DAV Public School, Bhubaneswar, India', dates: '2023', detail: '90.8%.' }, { degree: 'CBSE Class X', institution: 'DAV Public School, Bhubaneswar, India', dates: '2021', detail: '96.8%.' }],
  researchInterests: ['Biomaterials', 'Tissue Engineering', 'Regenerative Medicine', 'Hydrogels', 'Bioinks', 'Mechanical Characterization of Biomaterials', 'Polymer-Based Biomaterials', 'Mechanobiology', 'Computational Biomaterials', 'Molecular Dynamics', 'GROMACS', 'Biomedical Image Analysis'],
  projects: [
    { title: 'Mechanical Characterization of Biomaterial Systems', category: 'Biomaterials & Hydrogels', status: 'Research project', institution: 'National Institute of Technology Rourkela', supervisor: '', dates: '', overview: 'Work involving dextran methacrylate, gelatin methacrylate, and alginate methacrylate systems for hydrogel formulation and characterization.', objective: 'Explore material preparation and characterization approaches for hydrogel systems.', methods: ['Hydrogel formulation', 'Rheological characterization', 'UV-assisted crosslinking', 'Swelling and degradation studies'], tools: ['Anton Paar rheometer'], contribution: 'Experimental preparation and characterization support.', outcome: 'Ongoing academic work.', image: 'assets/images/biomaterials-project.png', featured: true, visible: true },
    { title: 'MARTINI 3-Based Molecular Dynamics Investigation of Nanoparticle–Membrane Interactions', category: 'Computational Biomaterials', status: 'Manuscript completed; intended for submission', institution: 'National Institute of Technology Rourkela', supervisor: '', dates: '2026', overview: 'A MARTINI 3-based molecular dynamics investigation of nanoparticle–membrane interactions.', objective: 'Use coarse-grained molecular dynamics and trajectory analysis to examine nanoparticle–membrane interactions.', methods: ['Coarse-grained molecular dynamics', 'Trajectory analysis'], tools: ['GROMACS', 'MARTINI 3'], contribution: 'Simulation and analysis workflow.', outcome: 'Manuscript completed; intended for peer-reviewed journal submission.', image: 'assets/images/molecular-dynamics-project.png', featured: true, visible: true },
    { title: 'Brain Tumor MRI Segmentation Using Deep Learning with GAN', category: 'Biomedical Image Analysis', status: 'Research project', institution: 'NIT Rourkela', supervisor: 'Prof. Sobhan Kanti Dhara', dates: 'Oct – Dec 2025', overview: 'MRI segmentation project combining U-Net segmentation with GAN-based synthetic image generation.', objective: 'Investigate automated brain-tumor segmentation from MRI images.', methods: ['MRI segmentation', 'U-Net', 'DCGAN-based synthetic image generation'], tools: ['Python', 'PyTorch', 'DCGAN', 'U-Net'], contribution: 'Developed and documented the deep-learning workflow.', outcome: 'Manuscript completed; intended for peer-reviewed journal submission.', image: 'assets/images/brain-tumor-project.jpg', github: 'https://github.com/PriyabrataDas1/brain-tumor-segmentation-gans', featured: true, visible: true },
    { title: 'Machine Learning-based Counterfeit Drug Detection', category: 'Computational Biomedical Research', status: 'Short-term research project', institution: 'ICMR', supervisor: 'Dr. Sangram Keshari Samal', dates: 'Jun 2026 – Present', overview: 'Ongoing project exploring machine-learning approaches for counterfeit pharmaceutical detection.', objective: 'Support drug authentication and pharmaceutical quality assessment through computational methods.', methods: ['Feature extraction', 'Classification', 'Predictive modelling'], tools: ['Python'], contribution: 'Exploring data-driven computational verification strategies.', outcome: 'Ongoing work.', image: '', featured: false, visible: true },
    { title: 'Muscle Fatigue Monitoring Using Surface Electromyography', category: 'Biomedical Instrumentation', status: 'Course project', institution: 'NIT Rourkela', supervisor: 'Prof. Earu Banoth', dates: 'Jan – Apr 2025', overview: 'Wearable biomedical instrumentation system for real-time forearm muscle-fatigue monitoring using surface electromyography.', objective: 'Integrate signal acquisition, processing, and threshold-based fatigue detection in a wearable system.', methods: ['Surface electromyography', 'Signal acquisition', 'Threshold-based fatigue detection'], tools: ['Arduino'], contribution: 'Integrated hardware and software workflows.', outcome: 'Course project.', image: 'assets/images/emg-project.jpg', github: 'https://github.com/PriyabrataDas1/muscle-fatigue-monitoring-emg', featured: false, visible: true },
  ],
  experience: [
    { organization: 'Institute of Life Sciences, Bhubaneswar', position: 'Research Intern', supervisor: 'Dr. Mamoni Dash', dates: 'May – Jul 2026', project: 'Mechanical Characterization of Alginate Methacrylate-Based Biomaterial Systems', responsibilities: ['Developed photocrosslinkable GelMA-, DexMA-, and alginate methacrylate-based biomaterial systems for regenerative medicine applications.', 'Performed biomaterial fabrication, mechanical characterization, cell-based studies, and computational workflows during the internship.'], methods: ['Mammalian cell culture', 'Oscillatory rheological characterization', 'MARTINI 3 coarse-grained molecular dynamics simulations'], skills: ['Hydrogel and scaffold mechanics', 'GROMACS', 'Biomaterial–membrane interaction studies'], visible: true },
    { organization: 'Indian Institute of Science, Bengaluru', position: 'Research Intern', supervisor: 'Prof. Debnath Pal', dates: 'May – Jun 2025', project: 'Biomedical Image Analysis using Machine Learning and Deep Learning', responsibilities: ['Investigated machine-learning and deep-learning approaches for biomedical image analysis using dental radiographs.', 'Developed and documented reproducible computational pipelines for feature extraction, anomaly detection, clustering, and semantic segmentation.'], methods: ['HOG', 'LBP', 'PCA', 'K-Means', 'DBSCAN', 'Isolation Forest', 'VGG16', 'CNNs', 'U-Net'], skills: ['Python', 'Computer vision', 'Open-source documentation'], visible: true },
    { organization: 'Institute of Life Sciences, Bhubaneswar', position: 'Research Intern', supervisor: 'Dr. Mamoni Dash', dates: 'May – Jun 2024', project: 'Analysis of Mechanical Properties of Soft Gels', responsibilities: ['Investigated collagen and alginate hydrogel systems for tissue engineering.', 'Assisted in the design, fabrication, and characterization of biomaterial systems while integrating molecular-biology techniques with tissue-engineering workflows.'], methods: ['Mammalian cell culture', 'Oscillatory rheology', 'RNA isolation', 'cDNA synthesis', 'RT-qPCR', 'IVIS imaging', 'Preclinical animal studies'], skills: ['Molecular biology', 'Translational biomaterials research'], visible: true },
    { organization: 'ICMR–Regional Medical Research Centre, Bhubaneswar', position: 'Research Intern', supervisor: 'Dr. Debdutta Bhattacharya', dates: 'Nov – Dec 2023', project: 'Molecular Diagnostics and Clinical Biomedical Research', responsibilities: ['Explored molecular diagnostics and clinical microbiology workflows for infectious disease detection.', 'Developed an understanding of standardized clinical laboratory workflows, biosafety practices, quality assurance procedures, and translational diagnostic applications.'], methods: ['DNA extraction', 'GeneXpert CBNAAT', 'VITEK 2 Compact', 'CLIA', 'Antimicrobial susceptibility testing', 'E-test', 'Qubit fluorometry'], skills: ['Clinical diagnostics', 'Microbial identification', 'Immunological assays'], visible: true },
    { organization: 'Fluxion Enterprise', position: 'Research Analyst', supervisor: '', dates: 'Jan 2026 – Present', project: 'Clinical AI and Predictive Healthcare Analytics', responsibilities: ['Developed multimodal clinical AI pipelines integrating vital signs, laboratory investigations, and clinical notes for continuous ICU risk assessment.', 'Designed predictive machine-learning models using longitudinal electronic health-record data.'], methods: ['Feature engineering', 'Temporal data integration', 'Missing-data handling', 'Model validation'], skills: ['Clinical AI', 'Predictive analytics'], visible: true },
  ],
  publications: { journalArticles: [], underReview: [], inPreparation: [{ title: 'MARTINI 3-Based Molecular Dynamics Investigation of Nanoparticle–Membrane Interactions', venue: '', doi: '', status: 'Manuscript completed; intended for submission to a peer-reviewed journal', type: 'Manuscript', year: '2026' }, { title: 'DCGAN-Based Synthetic MRI Augmentation for Brain Tumor Segmentation', venue: '', doi: '', status: 'Manuscript completed; intended for submission to a peer-reviewed journal', type: 'Manuscript', year: '2026' }], preprints: [], presentations: [{ title: 'Advancing Hepatitis-B Treatment through CLIA-Based Immune Profiling and Innovative Drug Development Strategies', venue: 'Young Scientists Conference (YSC), India International Science Festival (IISF), DBT-THSTI Campus, Faridabad, India', doi: '10.13140/RG.2.2.20983.64167', status: 'Presented', type: 'Conference presentation', year: 'Jan 2024', image: 'assets/images/conference-poster.jpg' }], posters: [] },
  skills: { Experimental: ['Biomaterial preparation', 'Hydrogel formulation', 'Rheology', 'UV-assisted crosslinking', 'Swelling and degradation studies', 'Basic cell culture', 'PCR and qPCR', 'RNA isolation', 'Laboratory documentation'], Computational: ['GROMACS', 'Molecular dynamics', 'Python', 'PyTorch', 'MATLAB', 'R', 'C++', 'Data analysis', 'Biomedical image analysis'], 'Software & tools': ['Git', 'GitHub', 'Linux', 'GraphPad Prism', 'Microsoft Word', 'Microsoft Excel', 'Microsoft PowerPoint', 'Canva', 'Arduino'] },
  achievements: ['GATE 2026 (Biomedical Engineering): AIR 251 (Top 6.7% nationwide)', 'IELTS Academic: Overall Band 7.5 (CEFR C1), 2026', 'Campus Innovation Challenge, IIEC, IISER Berhampur: Top 3 Finalist, 2024–25', 'Young Scientists Conference, India International Science Festival: Research Poster Presentation, 2024', 'National Talent Search Examination: Scholar (Top 1%), 2020–21', 'Indian Olympiad Qualifiers in Physics: Top 10%, 2021–22', 'Vidyarthi Vigyan Manthan: State Level Representative, Odisha, 2019–20', 'Singapore and Asian Schools Math Olympiad: Gold Award, 2018–19', 'Python for Machine Learning & Data Science – Jose Portilla (Udemy), 2025', 'INAE Technology Conclave 2026 attendee', 'Crime Codon, NIT Rourkela: Organization Head, 2024–25', 'TRUST: Say No To Blind-Beliefs: Volunteer, 2023–Present', 'TEDx DAV Public School Unit-VIII: Operations Team, 2021–22'],
  honorsAwards: ['GATE 2026 (Biomedical Engineering): AIR 251 (Top 6.7% nationwide)', 'Campus Innovation Challenge, IIEC, IISER Berhampur: Top 3 Finalist, 2024–25', 'Young Scientists Conference, India International Science Festival: Research Poster Presentation, 2024', 'National Talent Search Examination: Scholar (Top 1%), 2020–21', 'Indian Olympiad Qualifiers in Physics: Top 10%, 2021–22', 'Vidyarthi Vigyan Manthan: State Level Representative, Odisha, 2019–20', 'Singapore and Asian Schools Math Olympiad: Gold Award, 2018–19'],
  certifications: ['IELTS Academic: Overall Band 7.5 (CEFR C1), 2026', 'Python for Machine Learning & Data Science – Jose Portilla (Udemy), 2025'],
  professionalDevelopment: ['INAE Technology Conclave 2026, Indian National Academy of Engineering (INAE), Siksha ‘O’ Anusandhan University, Bhubaneswar, India'],
  leadershipService: ['Crime Codon, NIT Rourkela: Organization Head, 2024–25', 'TRUST: Say No To Blind-Beliefs: Volunteer, 2023–Present', 'TEDx DAV Public School Unit-VIII: Operations Team, 2021–22'],
  patents: [{ title: 'Multipurpose Cleaning Tool', application: 'Industrial Design Application No. 459636-001', organization: 'NRDC / Indian Patent Office', description: 'Co-developed a modular cleaning device with an adjustable telescopic mechanism and rotating cleaning assembly for elevated and difficult-to-access surfaces.' }, { title: 'AGRI-FLOW – A Compact Vertical Dryer', application: 'Patent / Industrial Design Application filed through NRDC', organization: 'NRDC / Indian Patent Office', description: 'Co-developed a compact agricultural dryer integrating vertical drying, automated moisture monitoring, and controlled drying for post-harvest loss reduction.' }],
  socialLinks: { github: 'https://github.com/PriyabrataDas1', linkedin: 'https://www.linkedin.com/in/priyabrata-das-74244033b/', scholar: '', orcid: '', researchgate: 'https://www.researchgate.net/profile/Priyabrata-Das-8' },
  siteSettings: { baseUrl: 'https://priyabratadas1.github.io', lastUpdated: '2026' }
};
