/* Renders shared portfolio data. The HTML contains useful static structure if JavaScript is unavailable. */
document.addEventListener('DOMContentLoaded', () => {
 const d=portfolioData, $=s=>document.querySelector(s), esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const menu=$('.menu-button'), list=$('.nav-list'); if(menu&&list){menu.addEventListener('click',()=>{let o=list.classList.toggle('open');menu.setAttribute('aria-expanded',o)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){list.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}})}
 document.querySelectorAll('[data-profile="name"]').forEach(e=>e.textContent=d.profile.name);document.querySelectorAll('[data-profile="intro"]').forEach(e=>e.textContent=d.profile.intro);document.querySelectorAll('[data-profile="availability"]').forEach(e=>{e.textContent=d.profile.availability;e.hidden=!d.profile.availability});
 document.querySelectorAll('[data-interests]').forEach(el=>el.innerHTML=d.researchInterests.map(x=>`<span class="tag">${esc(x)}</span>`).join(''));
 const media=p=>`<div class="project-media"><img src="${esc(p.image)}" alt="${esc(p.title)} project image" onerror="this.remove()"></div>`;
 const projectStatus=p=>{const value=String(p.status||'').toLowerCase();if(value.includes('manuscript'))return'Manuscript in Preparation';if(value.includes('ongoing')||value.includes('present')||value.includes('research project')||value.includes('short-term'))return'Ongoing';if(value.includes('internship')||value.includes('course project'))return'Completed';return p.status||''};
 const selectedResearchStatus=p=>{const value=String(p.status||'').toLowerCase();if(value.includes('manuscript'))return'Manuscript in Preparation';if(value.includes('internship')||value.includes('research project'))return'Research Internship Completed';return projectStatus(p)};
 const projectDescription=p=>[p.overview,p.contribution].filter(Boolean).map(esc).join(' ');
 const projectLinks=p=>[p.github&&`<a class="button secondary" href="${esc(p.github)}" target="_blank" rel="noopener noreferrer">GitHub</a>`,p.paper&&`<a class="button secondary" href="${esc(p.paper)}" target="_blank" rel="noopener noreferrer">Paper</a>`,p.poster&&`<a class="button secondary" href="${esc(p.poster)}" target="_blank" rel="noopener noreferrer">Poster</a>`].filter(Boolean).join('');
 const cards=(arr,featured=false)=>arr.filter(x=>x.visible!==false).map(p=>`<article class="card">${media(p)}<div class="card-body"><h3>${esc(p.title)}</h3><p class="meta">${[p.institution,p.dates||(featured?'2026':'')].filter(Boolean).map(esc).join(' · ')}</p><p>${projectDescription(p)}</p><p class="project-status">${esc(featured?selectedResearchStatus(p):projectStatus(p))}</p>${projectLinks(p)?`<div class="project-links">${projectLinks(p)}</div>`:''}</div></article>`).join('');
 document.querySelectorAll('[data-projects]').forEach(el=>{const featured=el.dataset.projects==='featured';el.innerHTML=cards(featured?d.projects.filter(p=>p.featured):d.projects,featured)});
 document.querySelectorAll('[data-education]').forEach(el=>el.innerHTML=d.education.map(x=>`<article><h3>${esc(x.degree)}</h3><p class="meta">${esc(x.institution)} - ${esc(x.dates)}</p><p>${esc(x.detail)}</p></article>`).join(''));
 const experienceCard=x=>`<article class="detail-card experience-card"><h3>${esc(x.organization)}</h3><p class="meta">${esc(x.position)}${x.dates?' · '+esc(x.dates):''}${x.supervisor?' · Supervisor: '+esc(x.supervisor):''}</p><p class="experience-project">${esc(x.project)}</p><ul>${(x.responsibilities||[]).slice(0,4).map(item=>`<li>${esc(item)}</li>`).join('')}</ul>${x.active?'<p class="project-status">Ongoing</p>':''}</article>`;
 document.querySelectorAll('[data-experience]').forEach(el=>{const internships=el.dataset.experience==='internships';el.innerHTML=d.experience.filter(x=>x.visible&&(internships?x.position==='Research Intern':x.position!=='Research Intern')).map(experienceCard).join('')});
 document.querySelectorAll('[data-skills]').forEach(el=>el.innerHTML=Object.entries(d.skills).map(([k,v])=>`<article class="detail-card"><h3>${esc(k)}</h3><div class="tags">${v.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></article>`).join(''));
 const achievement=x=>{const [name,...detail]=String(x).split(':');return `<li><strong>${esc(name)}</strong>${detail.length?`: ${esc(detail.join(':').trim())}`:''}</li>`};document.querySelectorAll('[data-achievements]').forEach(el=>{el.innerHTML=d.achievements.map(achievement).join('');el.insertAdjacentHTML('afterend','<figure class="achievement-proof"><img src="assets/images/iisf-poster-presentation.png" alt="Priyabrata Das presenting a poster at the IISF Young Scientists Conference 2023"><figcaption>Poster presentation at the Young Scientists Conference (IISF 2023), Faridabad, India</figcaption></figure>')});
 const pub=d.publications; const publicationCard=(item,type)=>type==='manuscript'?`<article class="detail-card publication-card"><h3>${esc(item.title)}</h3><p class="meta">Status: ${esc(item.status)}</p></article>`:`<article class="detail-card publication-card"><h3>${esc(item.title)}</h3><p>${esc(item.conference||item.venue||'')}</p>${item.location?`<p>${esc(item.location)}</p>`:''}<p class="meta">${esc(item.status)}</p>${item.doi?`<p><a href="https://doi.org/${esc(item.doi)}" target="_blank" rel="noopener noreferrer">DOI: ${esc(item.doi)}</a></p>`:''}</article>`; document.querySelectorAll('[data-publications]').forEach(el=>el.innerHTML=`<section><h2>Manuscripts in Preparation</h2>${pub.inPreparation.map(item=>publicationCard(item,'manuscript')).join('')}</section><section><h2>Conference Presentations</h2>${pub.presentations.map(item=>publicationCard(item,'presentation')).join('')}</section>`);
 const socials={github:'GitHub',linkedin:'LinkedIn',scholar:'Google Scholar',orcid:'ORCID',researchgate:'ResearchGate'};document.querySelectorAll('[data-socials]').forEach(el=>el.innerHTML=Object.entries(socials).filter(([k])=>d.socialLinks[k]).map(([k,n])=>`<a href="${esc(d.socialLinks[k])}" target="_blank" rel="noopener noreferrer">${n}</a>`).join(' - '));
 document.querySelectorAll('[data-email]').forEach(el=>{el.href='mailto:'+d.profile.email;el.textContent=d.profile.email});
 const cv=$('[cv-viewer]');if(cv){cv.innerHTML=`<object class="cv-viewer" data="${d.profile.cvPath}" type="application/pdf"><p>PDF preview is unavailable. <a href="${d.profile.cvPath}">Download the CV</a>.</p></object>`}
 document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());
});
